language: node_js
node_js: 8.7
addons:
  firefox: "51.0"
install:
  - npm install
before_install:
  - "export DISPLAY=:99.0"
  - "export DEBUG=testee:*"
  - "sh -e /etc/init.d/xvfb start"
notifications:
  slack: txuniverse:O1XW4GuJH91iHr71md4n7rsl