version: 2

jobs:
  build:
    docker:
      - image: circleci/node:7.10 
    working_directory: ~/build
    steps:
      - checkout
      - run: npm install donejs -g
      - run: npm install
      - run: donejs build
      
general:
  branches:
    only:
      - devops/qa
